Update readme and URLs
open-ephys/bonsai-onix1 pull request #350
Opened 2024-10-28 01:59 UTC by cjsha

The important thing from this PR is that we need to update the URLs (after the repo name changed) so that the nodes that are published on nuget are linked to the actual docs site. Currently the "F1" Help functionality doesn't work for our nodes. I think this should fix that.

I also added some instructions to the README to document how to setup breakpoints in Visual Studio.

2024-10-28 12:58 UTC, jonnew commented on README.md
> +
If you are going to provide information on this, then you have to also provide instructions in installing the child process debugging extension in VS:

<img width="1338" alt="image" src="https://github.com/user-attachments/assets/92d93ebc-8c3b-45d8-ac56-9780a30de7d1">

2024-10-28 12:59 UTC, jonnew commented on README.md
> +1. Enable mixed debugging
mixed debugging -> native code debugging

2024-10-28 13:01 UTC, jonnew requested changes
Instead of random snippets with no context:

<img width="251" alt="image" src="https://github.com/user-attachments/assets/535dde79-5aba-48aa-afd5-2375b8f700fe">

<img width="468" alt="image" src="https://github.com/user-attachments/assets/d17b175f-d6de-4745-8fa4-d63dc9d36a63">

Just show the compete dialog with steps labelled as in the original image in this readme, or no labels if its obvious

2024-10-28 14:01 UTC, bparks13 requested changes
I addressed all of the comments by @jonnew, and I updated the version number so that the actions would pass.

However, I noticed that in the `build-and-run.png` file, there is only the numbers for 3 and 4. Did we change the image?

2024-10-28 20:11 UTC, cjsha commented
I haven't changed `build-and-run.png`. I just moved it to a different images folder. In any case, I think the way it is makes sense - labels 3 & 4 correspond to bullet points 3 & 4 of the "Run in visual studio" section. I'm not sure bullet points 1 & 2 need screenshots w/ labels.

I don't think we had it like jon does in the "[Enable Debugging](https://github.com/open-ephys/bonsai-onix1/tree/update-README-and-URLs?tab=readme-ov-file#enable-debugging)" section that we'd created. In the latest commit, I try to amend that.

Thanks for addressing his comments @bparks13

2024-10-29 13:31 UTC, bparks13 approved these changes
Everything looks good to me now, but there are a few commits going back and forth; before merging to main, I would recommend someone go through and squash commits together to clean up the history

2024-10-29 13:35 UTC, jonnew approved these changes

2024-10-29 13:35 UTC, jonnew commented
@cjsha please squash and merge

2024-10-29 14:33 UTC, merged