Add voltage conversion equations to Neuropixels DataFrame docs
open-ephys/bonsai-onix1 pull request #367
Opened 2024-11-05 16:09 UTC by jonnew

- Fixes #358

2024-11-06 23:55 UTC, jsiegle requested changes

2024-11-06 23:55 UTC, jsiegle commented on OpenEphys.Onix1/NeuropixelsV2eBetaDataFrame.cs
> +        /// V_electrode (uV) = 0.91553 uV × (ADC result – 8192)
The equation I've been using is 1/80/pow(2,14)*1e6 = 0.7629 uV

2024-11-06 23:55 UTC, jsiegle commented on OpenEphys.Onix1/NeuropixelsV2eDataFrame.cs
> +        /// V_electrode (uV) = 2.44141 uV × (ADC result – 2048)
See above...

1/80/pow(2,12)*1e6 = 3.05176 uV

2024-11-06 23:55 UTC, jsiegle commented on OpenEphys.Onix1/NeuropixelsV2eDataFrame.cs
> +        /// V_electrode (uV) = 2.44141 uV × (ADC result – 2048)
Volts per bit should be exactly 4x higher than for the beta probes

2024-11-07 14:30 UTC, jonnew commented on OpenEphys.Onix1/NeuropixelsV2eDataFrame.cs
> +        /// V_electrode (uV) = 2.44141 uV × (ADC result – 2048)
I get the 4x thing (14->12 bit) but I see this on the data sheet: 

![image](https://github.com/user-attachments/assets/83aeac57-7f29-4755-a6f0-5c088f9370dc)

is it 80 or 100 for the public version?

2024-11-07 14:30 UTC, jonnew commented on OpenEphys.Onix1/NeuropixelsV2eBetaDataFrame.cs
> +        /// V_electrode (uV) = 0.91553 uV × (ADC result – 8192)
That makes sense, not sure where I got my number from tbh.

2024-11-07 14:33 UTC, jonnew commented on OpenEphys.Onix1/NeuropixelsV2eDataFrame.cs
> +        /// V_electrode (uV) = 2.44141 uV × (ADC result – 2048)
This on latest brochure as well

https://www.neuropixels.org/_files/ugd/328966_2b39661f072d405b8d284c3c73588bc6.pdf

2024-12-09 17:46 UTC, cjsha commented
hey y'all. Just commenting to bring attention to this PR for the purpose of accurately populating this page:
https://open-ephys.github.io/bonsai-onix1-docs/articles/getting-started/reference.html
Thanks

2024-12-10 21:36 UTC, jsiegle commented on OpenEphys.Onix1/NeuropixelsV2eDataFrame.cs
> +        /// V_electrode (uV) = 2.44141 uV × (ADC result – 2048)
I was confused about that as well – but I confirmed that there is exactly a 4x difference by putting beta and commercial probes in the same saline bath

2024-12-18 17:01 UTC, cjsha commented
This is how my edits render:
![image](https://github.com/user-attachments/assets/1deea9b8-43ea-4c9a-8458-58ae51933623)
![image](https://github.com/user-attachments/assets/e44225b6-5250-4f25-9eb3-4a51da19a5dc)

2025-01-02 17:52 UTC, jonnew commented
I think this is ready to go. Ill merge when approved by @jsiegle

2025-01-04 00:17 UTC, jsiegle approved these changes

2025-01-06 17:17 UTC, cjsha commented
This could go in 0.4.3

2025-02-10 20:46 UTC, jonnew commented
@bparks13 when you have a moment, can you let me know what is going on with the checks for this PR? Two of them appear to be stuck. As soon as that's resolved we should merge this.

2025-02-18 16:24 UTC, merged